export const T = {
  welcome:{it:"Benvenuti",en:"Welcome",es:"Bienvenidos",fr:"Bienvenue",de:"Willkommen"},
  greetMorning:{it:"Buongiorno",en:"Good morning",es:"Buenos días",fr:"Bonjour",de:"Guten Morgen"},
  greetAfternoon:{it:"Buon pomeriggio",en:"Good afternoon",es:"Buenas tardes",fr:"Bon après-midi",de:"Guten Tag"},
  greetEvening:{it:"Buonasera",en:"Good evening",es:"Buenas noches",fr:"Bonsoir",de:"Guten Abend"},
  heroSub:{it:"Tutto ciò che serve per un soggiorno sereno a Sondrio.",en:"Everything you need for a restful stay in Sondrio.",es:"Todo lo necesario para una estancia tranquila en Sondrio.",fr:"Tout le nécessaire pour un séjour paisible à Sondrio.",de:"Alles für einen erholsamen Aufenthalt in Sondrio."},
  getDirections:{it:"Indicazioni stradali",en:"Get directions",es:"Cómo llegar",fr:"Itinéraire",de:"Route berechnen"},
  loopTag:{it:"Video in loop",en:"Looped vibe video",es:"Vídeo en bucle",fr:"Vidéo en boucle",de:"Loop-Video"},
  welcomeNote:{it:"Siamo felici di ospitarvi. Qui trovate tutto ciò che serve per sentirvi a casa.",en:"We're so glad you're here. Here's everything you need to feel at home.",es:"Nos alegra teneros aquí. Aquí está todo para que os sintáis como en casa.",fr:"Ravis de vous accueillir. Voici tout pour vous sentir chez vous.",de:"Schön, dass Sie da sind. Hier ist alles, damit Sie sich wie zu Hause fühlen."},
  sig:{it:"Con affetto, Stephanie e Julian",en:"With love, Stephanie & Julian",es:"Con cariño, Stephanie y Julian",fr:"Avec toute notre affection, Stephanie & Julian",de:"Herzlich, Stephanie & Julian"},
  arrival:{it:"Arrivo e partenza",en:"Arrival & departure",es:"Llegada y salida",fr:"Arrivée & départ",de:"Ankunft & Abreise"},
  tabArrival:{it:"Arrivo",en:"Arrival",es:"Llegada",fr:"Arrivée",de:"Ankunft"},
  tabDeparture:{it:"Partenza",en:"Departure",es:"Salida",fr:"Départ",de:"Abreise"},
  checkinFrom:{it:"Check-in dalle",en:"Check-in from",es:"Entrada desde",fr:"Arrivée dès",de:"Check-in ab"},
  doorCode:{it:"Codice porta",en:"Door code",es:"Código puerta",fr:"Code porte",de:"Türcode"},
  checkoutBy:{it:"Check-out entro",en:"Check-out by",es:"Salida antes de",fr:"Départ avant",de:"Check-out bis"},
  departSteps:{it:"Prima di partire: rifiuti fuori, lavastoviglie avviata, chiavi nella cassetta.",en:"Before you go: bins out, dishwasher on, keys back in the lockbox.",es:"Antes de salir: basura fuera, lavavajillas puesto, llaves en la caja.",fr:"Avant de partir : poubelles sorties, lave-vaisselle lancé, clés dans la boîte.",de:"Vor der Abreise: Müll raus, Spülmaschine an, Schlüssel in die Box."},
  coTitle:{it:"Prima di partire",en:"Before you go",es:"Antes de salir",fr:"Avant de partir",de:"Vor der Abreise"},
  coItem1:{it:"Rifiuti fuori",en:"Bins out",es:"Basura fuera",fr:"Poubelles sorties",de:"Müll raus"},
  coItem2:{it:"Lavastoviglie avviata",en:"Dishwasher on",es:"Lavavajillas puesto",fr:"Lave-vaisselle lancé",de:"Spülmaschine an"},
  coItem3:{it:"Chiavi nella cassetta",en:"Keys in the lockbox",es:"Llaves en la caja",fr:"Clés dans la boîte",de:"Schlüssel in die Box"},
  coDone:{it:"Tutto pronto, buon viaggio!",en:"All set, safe travels!",es:"¡Todo listo, buen viaje!",fr:"Tout est prêt, bon voyage !",de:"Alles erledigt, gute Reise!"},
  wifi:{it:"Wi-Fi",en:"Wi-Fi",es:"Wi-Fi",fr:"Wi-Fi",de:"WLAN"},
  network:{it:"Rete",en:"Network",es:"Red",fr:"Réseau",de:"Netzwerk"},
  password:{it:"Password",en:"Password",es:"Contraseña",fr:"Mot de passe",de:"Passwort"},
  inclTitle:{it:"Tutto qui",en:"Everything's here",es:"Todo aquí",fr:"Tout est là",de:"Alles da"},
  evName:{it:"Ricarica auto",en:"EV charger",es:"Cargador VE",fr:"Recharge VE",de:"E-Ladestation"},
  evSub:{it:"22 kW, proprio fuori dalla porta",en:"22 kW, right outside the door",es:"22 kW, justo en la puerta",fr:"22 kW, juste devant la porte",de:"22 kW, direkt vor der Tür"},
  amKitchen:{it:"Cucina",en:"Kitchen",es:"Cocina",fr:"Cuisine",de:"Küche"},
  amLaundry:{it:"Lavanderia",en:"Laundry",es:"Lavandería",fr:"Buanderie",de:"Wäsche"},
  amComfort:{it:"Comfort",en:"Comfort",es:"Confort",fr:"Confort",de:"Komfort"},
  c1:{it:"Caffè",en:"Coffee",es:"Café",fr:"Café",de:"Kaffee"},
  c2:{it:"Lavatrice",en:"Washer",es:"Lavadora",fr:"Lave-linge",de:"Waschmaschine"},
  c5:{it:"Asciugatrice",en:"Dryer",es:"Secadora",fr:"Sèche-linge",de:"Trockner"},
  c3:{it:"Biancheria",en:"Fresh linens",es:"Ropa de cama",fr:"Linge de maison",de:"Frische Wäsche"},
  c4:{it:"Riscaldamento",en:"Heating",es:"Calefacción",fr:"Chauffage",de:"Heizung"},
  cDish:{it:"Lavastoviglie",en:"Dishwasher",es:"Lavavajillas",fr:"Lave-vaisselle",de:"Geschirrspüler"},
  cOven:{it:"Forno",en:"Oven",es:"Horno",fr:"Four",de:"Backofen"},
  cStove:{it:"Piano cottura a gas",en:"Gas stove",es:"Cocina de gas",fr:"Cuisinière à gaz",de:"Gasherd"},
  cMicro:{it:"Microonde",en:"Microwave",es:"Microondas",fr:"Micro-ondes",de:"Mikrowelle"},
  cBidet:{it:"Bidet",en:"Bidet",es:"Bidé",fr:"Bidet",de:"Bidet"},
  nbTitle:{it:"Il quartiere",en:"The neighbourhood",es:"El barrio",fr:"Le quartier",de:"Die Nachbarschaft"},
  nbText:{it:"Tutto a pochi minuti a piedi.",en:"Everything's a few minutes on foot.",es:"Todo a pocos minutos a pie.",fr:"Tout à quelques minutes à pied.",de:"Alles wenige Gehminuten entfernt."},
  nbTrain:{it:"Treno per Milano",en:"Train to Milan",es:"Tren a Milán",fr:"Train pour Milan",de:"Zug nach Mailand"},
  nbGrocery:{it:"Supermercato",en:"Grocery",es:"Supermercado",fr:"Supermarché",de:"Supermarkt"},
  nbPiazza:{it:"Piazza principale",en:"Main piazza",es:"Plaza principal",fr:"Place principale",de:"Hauptplatz"},
  nbFood:{it:"Ristoranti",en:"Restaurants",es:"Restaurantes",fr:"Restaurants",de:"Restaurants"},
  dtTitle:{it:"Gite in giornata",en:"Day trips",es:"Excursiones de un día",fr:"Excursions d'une journée",de:"Tagesausflüge"},
  dtText:{it:"Alcune delle nostre fughe preferite, tutte a portata di mano.",en:"Some of our favourite escapes, all within easy reach.",es:"Algunas de nuestras escapadas favoritas, muy cerca.",fr:"Quelques-unes de nos escapades préférées, tout près.",de:"Einige unserer Lieblingsausflüge, alle gut erreichbar."},
  dtComoD:{it:"Cittadine sul lago, ville e giardini iconici.",en:"Iconic lakeside towns, villas and gardens.",es:"Pueblos junto al lago, villas y jardines icónicos.",fr:"Villages au bord du lac, villas et jardins emblématiques.",de:"Ikonische Seeorte, Villen und Gärten."},
  dtTiranoD:{it:"Dove inizia il panoramico Bernina Express.",en:"Where the scenic Bernina Express begins.",es:"Donde empieza el panorámico Bernina Express.",fr:"Le départ du panoramique Bernina Express.",de:"Startpunkt des landschaftlichen Bernina Express."},
  dtBormioD:{it:"Località sciistica alpina con terme storiche.",en:"Alpine ski town with historic thermal spas.",es:"Estación de esquí alpina con termas históricas.",fr:"Station de ski alpine aux thermes historiques.",de:"Alpiner Skiort mit historischen Thermen."},
  dtStMoritzD:{it:"Elegante località alpina svizzera oltre confine.",en:"Glamorous Swiss alpine resort over the border.",es:"Glamurosa estación alpina suiza al otro lado.",fr:"Station alpine suisse chic de l'autre côté.",de:"Mondäner Schweizer Alpenort jenseits der Grenze."},
  dtCar:{it:"Volete noleggiare un'auto? Hertz e Avis hanno uffici a Sondrio.",en:"Renting a car? Hertz and Avis both have offices in Sondrio.",es:"¿Alquilar coche? Hertz y Avis tienen oficinas en Sondrio.",fr:"Louer une voiture ? Hertz et Avis ont des bureaux à Sondrio.",de:"Auto mieten? Hertz und Avis haben Büros in Sondrio."},
  bandStay:{it:"Una foto ampia dell'appartamento",en:"A wide shot of the apartment",es:"Una foto amplia del apartamento",fr:"Une vue large de l'appartement",de:"Eine Weitwinkelaufnahme der Wohnung"},
  bandVibe:{it:"Un'immagine d'atmosfera della valle e della luce",en:"A vibe shot of the valley and the light",es:"Una foto de ambiente del valle y la luz",fr:"Une image d'ambiance de la vallée et la lumière",de:"Ein Stimmungsbild vom Tal und dem Licht"},
  hostsSub:{it:"I vostri host · rispondiamo in pochi minuti",en:"Your hosts · reply within minutes",es:"Vuestros anfitriones · respondemos en minutos",fr:"Vos hôtes · réponse en quelques minutes",de:"Ihre Gastgeber · Antwort in Minuten"},
  emTitle:{it:"Emergenze",en:"Emergency",es:"Emergencias",fr:"Urgences",de:"Notfall"},
  emText:{it:"Il 112 raggiunge ambulanza, vigili del fuoco e polizia da qualsiasi telefono.",en:"112 reaches ambulance, fire and police from any phone.",es:"El 112 conecta con ambulancia, bomberos y policía desde cualquier teléfono.",fr:"Le 112 joint l'ambulance, les pompiers et la police depuis n'importe quel téléphone.",de:"Die 112 erreicht Rettung, Feuerwehr und Polizei von jedem Telefon."},
  emServices:{it:"Numero unico emergenze",en:"Emergency services",es:"Servicios de emergencia",fr:"Services d'urgence",de:"Notdienste"},
  emPharmacy:{it:"Farmacia più vicina",en:"Nearest pharmacy",es:"Farmacia más cercana",fr:"Pharmacie la plus proche",de:"Nächste Apotheke"},
  ttSub:{it:"Cose da fare, per stagione",en:"Things to do, by season",es:"Qué hacer, por temporada",fr:"À faire, par saison",de:"Aktivitäten, je Saison"},
  seasonWinter:{it:"Inverno",en:"Winter",es:"Invierno",fr:"Hiver",de:"Winter"},
  seasonSummer:{it:"Estate",en:"Summer",es:"Verano",fr:"Été",de:"Sommer"},
  seasonAll:{it:"Tutto l'anno",en:"Year-round",es:"Todo el año",fr:"Toute l'année",de:"Ganzjährig"},
  actSki:{it:"Sci a Bormio e Santa Caterina",en:"Ski Bormio & Santa Caterina",es:"Esquí en Bormio y Santa Caterina",fr:"Ski à Bormio & Santa Caterina",de:"Skifahren in Bormio & Santa Caterina"},
  actSkiD:{it:"Piste di livello mondiale e lo Stelvio, a circa un'ora.",en:"World-class pistes and the Stelvio, about an hour away.",es:"Pistas de primer nivel y el Stelvio, a una hora.",fr:"Pistes de niveau mondial et le Stelvio, à environ une heure.",de:"Weltklasse-Pisten und das Stilfserjoch, etwa eine Stunde entfernt."},
  actHike:{it:"Cammina sui sentieri della valle",en:"Hike the valley trails",es:"Camina por los senderos del valle",fr:"Randonnée sur les sentiers de la vallée",de:"Wandern auf den Talwegen"},
  actHikeD:{it:"Decine di sentieri segnati, da facili passeggiate a percorsi alpini.",en:"Dozens of marked trails, from gentle valley walks to alpine routes.",es:"Decenas de senderos señalizados, de paseos suaves a rutas alpinas.",fr:"Des dizaines de sentiers balisés, de balades faciles aux itinéraires alpins.",de:"Dutzende markierte Wege, von leichten Talwanderungen bis zu alpinen Routen."},
  actClimb:{it:"Arrampicata e vie ferrate",en:"Rock climbing & via ferrata",es:"Escalada y vías ferratas",fr:"Escalade et via ferrata",de:"Klettern & Klettersteige"},
  actClimbD:{it:"Falesie e vie ferrate in tutta la valle.",en:"Crags and via ferrata routes across the valley.",es:"Riscos y vías ferratas por todo el valle.",fr:"Falaises et via ferrata dans toute la vallée.",de:"Felsen und Klettersteige im ganzen Tal."},
  actWine:{it:"Degustazione di vini della Valtellina",en:"Valtellina wine tasting",es:"Cata de vinos de Valtellina",fr:"Dégustation de vins de Valteline",de:"Valtellina-Weinprobe"},
  actWineD:{it:"Rossi di Nebbiolo e cantine terrazzate, a pochi minuti.",en:"Nebbiolo reds and terraced cellars, minutes away.",es:"Tintos de Nebbiolo y bodegas en terrazas, a pocos minutos.",fr:"Rouges de Nebbiolo et caves en terrasses, à quelques minutes.",de:"Nebbiolo-Rotweine und Terrassenkeller, wenige Minuten entfernt."},
  actTerme:{it:"Terme di Bormio",en:"Bormio thermal baths",es:"Termas de Bormio",fr:"Thermes de Bormio",de:"Thermen von Bormio"},
  actTermeD:{it:"Bagni Vecchi e Bagni Nuovi, spa storiche e moderne.",en:"Bagni Vecchi and Bagni Nuovi, historic and modern spas.",es:"Bagni Vecchi y Bagni Nuovi, termas históricas y modernas.",fr:"Bagni Vecchi et Bagni Nuovi, thermes historiques et modernes.",de:"Bagni Vecchi und Bagni Nuovi, historische und moderne Thermen."},
  actBernina:{it:"Bernina Express",en:"Bernina Express",es:"Bernina Express",fr:"Bernina Express",de:"Bernina Express"},
  actBerninaD:{it:"Ferrovia alpina UNESCO fino a St. Moritz, partenza da Tirano.",en:"UNESCO alpine railway to St. Moritz, boarding at Tirano.",es:"Ferrocarril alpino UNESCO a St. Moritz, desde Tirano.",fr:"Chemin de fer alpin UNESCO vers St-Moritz, départ à Tirano.",de:"UNESCO-Alpenbahn nach St. Moritz, Einstieg in Tirano."},
  gVineyards:{it:"Vigneti",en:"Vineyards",es:"Viñedos",fr:"Vignes",de:"Weinberge"},
  gTrails:{it:"Sentieri",en:"Trails",es:"Senderos",fr:"Sentiers",de:"Wanderwege"},
  gTown:{it:"Il centro",en:"Old town",es:"Casco antiguo",fr:"Vieille ville",de:"Altstadt"},
  contactHost:{it:"Contatta l'host",en:"Contact host",es:"Contactar",fr:"Contacter l'hôte",de:"Gastgeber kontakt"},
  callHostShort:{it:"Chiama",en:"Call",es:"Llamar",fr:"Appeler",de:"Anrufen"},
  waHost:{it:"WhatsApp",en:"WhatsApp",es:"WhatsApp",fr:"WhatsApp",de:"WhatsApp"},
  peekTitle:{it:"Uno sguardo dentro",en:"A peek inside",es:"Un vistazo dentro",fr:"Un aperçu de l'intérieur",de:"Ein Blick hinein"},
  peekText:{it:"Alcuni scorci della casa.",en:"A few glimpses of the place.",es:"Algunos rincones de la casa.",fr:"Quelques aperçus du logement.",de:"Ein paar Eindrücke der Wohnung."},
  pBedroom:{it:"Camera",en:"Bedroom",es:"Dormitorio",fr:"Chambre",de:"Schlafzimmer"},
  pLiving:{it:"Soggiorno",en:"Living room",es:"Salón",fr:"Salon",de:"Wohnzimmer"},
  pKitchen:{it:"Cucina",en:"Kitchen",es:"Cocina",fr:"Cuisine",de:"Küche"},
  pBathroom:{it:"Bagno",en:"Bathroom",es:"Baño",fr:"Salle de bain",de:"Badezimmer"},
  pBathSteam:{it:"Bagno · doccia a vapore",en:"Bathroom · steam shower",es:"Baño · ducha de vapor",fr:"Salle de bain · douche vapeur",de:"Bad · Dampfdusche"},
  pOffice:{it:"Studio",en:"Office",es:"Despacho",fr:"Bureau",de:"Arbeitszimmer"},
  pOfficeSofa:{it:"Studio · divano letto",en:"Office · sofa bed",es:"Despacho · sofá cama",fr:"Bureau · canapé-lit",de:"Arbeitszimmer · Schlafsofa"},
  specSleeps:{it:"4 posti letto",en:"Sleeps 4",es:"Para 4 personas",fr:"4 couchages",de:"4 Schlafplätze"},
  specBeds:{it:"Matrimoniale + divano letto",en:"Queen + sofa bed",es:"Cama de matrimonio + sofá cama",fr:"Lit double + canapé-lit",de:"Doppelbett + Schlafsofa"},
  specBath:{it:"1 bagno, doccia a vapore",en:"1 bathroom, steam shower",es:"1 baño, ducha de vapor",fr:"1 salle de bain, douche vapeur",de:"1 Bad, Dampfdusche"},
  pFoyer:{it:"Ingresso",en:"Entryway",es:"Entrada",fr:"Entrée",de:"Eingang"},
  pLaundry:{it:"Lavanderia",en:"Laundry",es:"Lavadero",fr:"Buanderie",de:"Waschraum"},
  shortClip:{it:"Video breve",en:"Short clip",es:"Clip corto",fr:"Clip court",de:"Kurzes Video"},
  addPhoto:{it:"aggiungi foto",en:"add photo",es:"añadir foto",fr:"ajouter photo",de:"Foto einfügen"},
  addVideo:{it:"aggiungi video",en:"add video",es:"añadir vídeo",fr:"ajouter vidéo",de:"Video einfügen"},
  exploreTitle:{it:"Esplora la Valtellina",en:"Explore Valtellina",es:"Explora Valtellina",fr:"Explorer la Valteline",de:"Valtellina entdecken"},
  exploreText:{it:"Sentieri, cantine e i nostri posti preferiti, a pochi passi.",en:"Trails, wine cellars and our favourite spots, minutes from the door.",es:"Senderos, bodegas y nuestros lugares favoritos, a pocos pasos.",fr:"Sentiers, caves et nos coins préférés, à deux pas.",de:"Wege, Weinkeller und unsere Lieblingsorte, nur Minuten entfernt."},
  openMaps:{it:"Apri la mappa",en:"Open map",es:"Abrir mapa",fr:"Ouvrir la carte",de:"Karte öffnen"},
  emergency:{it:"Emergenze e host",en:"Emergency & host",es:"Emergencias y anfitrión",fr:"Urgences & hôte",de:"Notfall & Gastgeber"},
  emNum:{it:"Emergenze",en:"Emergency",es:"Emergencias",fr:"Urgences",de:"Notruf"},
  callHost:{it:"Chiama l'host",en:"Call host",es:"Llamar al anfitrión",fr:"Appeler l'hôte",de:"Gastgeber anrufen"},
  copy:{it:"Copia",en:"Copy",es:"Copiar",fr:"Copier",de:"Kopieren"},
  copied:{it:"Copiato",en:"Copied",es:"Copiado",fr:"Copié",de:"Kopiert"},
  privacyText:{it:"Il codice d'ingresso e il Wi-Fi sono riservati agli ospiti.",en:"Your check-in code and Wi-Fi are private to guests.",es:"Tu código de entrada y el Wi-Fi son privados para los huéspedes.",fr:"Votre code d'entrée et le Wi-Fi sont réservés aux hôtes.",de:"Ihr Zugangscode und WLAN sind nur für Gäste."},
  unlock:{it:"Sblocca",en:"Unlock",es:"Desbloquear",fr:"Déverrouiller",de:"Freischalten"},
  unlockedMsg:{it:"Sbloccato per il tuo soggiorno",en:"Unlocked for your stay",es:"Desbloqueado para tu estancia",fr:"Déverrouillé pour votre séjour",de:"Für Ihren Aufenthalt freigeschaltet"},
  eatTitle:{it:"Dove mangiare",en:"Where to eat",es:"Dónde comer",fr:"Où manger",de:"Wo essen"},
  eat1:{it:"Enoteca e wine bar con piatti alpini.",en:"Wine bar and enoteca with alpine small plates.",es:"Enoteca y wine bar con platos alpinos.",fr:"Bar à vins et enoteca, petites assiettes alpines.",de:"Weinbar und Enoteca mit alpinen Häppchen."},
  eat2:{it:"Trattoria valtellinese classica, pizzoccheri e non solo.",en:"Classic Valtellina trattoria, pizzoccheri and more.",es:"Trattoria clásica de Valtellina, pizzoccheri y más.",fr:"Trattoria valtellinaise classique, pizzoccheri et plus.",de:"Klassische Valtellina-Trattoria, Pizzoccheri und mehr."},
  eat3:{it:"Pizza al forno a legna, amata dai locali.",en:"Wood-fired pizza, a local favourite.",es:"Pizza al horno de leña, favorita local.",fr:"Pizza au feu de bois, un incontournable local.",de:"Holzofenpizza, ein lokaler Favorit."},
  accessPhrase:{it:"Frase d'accesso",en:"Access phrase",es:"Frase de acceso",fr:"Phrase d'acces",de:"Zugangsphrase"},
  tryAgain:{it:"Riprova",en:"Try again",es:"Inténtalo de nuevo",fr:"Réessayez",de:"Erneut versuchen"},
  gbTitle:{it:"Diario degli ospiti",en:"Guestbook",es:"Libro de visitas",fr:"Livre d'or",de:"Gästebuch"},
  gbText:{it:"Qualche pensiero di chi è stato qui prima di voi.",en:"A few words from guests who came before you.",es:"Unas palabras de quienes estuvieron antes que vosotros.",fr:"Quelques mots de voyageurs passés avant vous.",de:"Ein paar Worte von Gästen vor Ihnen."},
  gbEmpty:{it:"Sarete i primi a lasciare un pensiero.",en:"Be the first to leave a note.",es:"Sé el primero en dejar una nota.",fr:"Soyez les premiers à laisser un mot.",de:"Hinterlassen Sie den ersten Gruß."},
  gbLeave:{it:"Lascia un pensiero",en:"Leave us a note",es:"Déjanos una nota",fr:"Laissez-nous un mot",de:"Hinterlassen Sie einen Gruß"},
  gbWaMsg:{it:"Ciao! Vorremmo lasciare un pensiero sul nostro soggiorno: ",en:"Hi! We'd love to leave a note about our stay: ",es:"¡Hola! Nos gustaría dejar una nota sobre nuestra estancia: ",fr:"Bonjour ! Nous aimerions laisser un mot sur notre séjour : ",de:"Hallo! Wir möchten einen Gruß zu unserem Aufenthalt hinterlassen: "},
  soTitle:{it:"A presto",en:"Come back soon",es:"Vuelve pronto",fr:"À bientôt",de:"Bis bald"},
  soText:{it:"Grazie per essere stati con noi. Ci piacerebbe rivedervi in un'altra stagione.",en:"Thank you for staying with us. We'd love to see you back in another season.",es:"Gracias por quedaros con nosotros. Nos encantaría veros en otra estación.",fr:"Merci d'avoir séjourné chez nous. Au plaisir de vous revoir à une autre saison.",de:"Danke für Ihren Aufenthalt. Wir würden uns freuen, Sie in einer anderen Jahreszeit wiederzusehen."}
};
